FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY artifacts/core-service.jar app.jar

RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]

