FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY artifacts/notification-service.jar app.jar

RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

EXPOSE 10081

ENTRYPOINT ["java", "-jar", "app.jar"]

